import type { Metadata } from "next";
import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';
import "./globals.css";
import Head from 'next/head';


export const metadata: Metadata = {
  title: "Creative Landing Page",
  description: "Generated by MRA",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/favicon.svg" sizes="any" type="image/svg+xml" />
      </Head>
      <body
        className={`${GeistSans.className} ${GeistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
